spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: news-service
          uri: lb://NEWS-SERVICE
          predicates:
            - Path=/api/posts/**
          filters:
            - AuthenticationFilter

        - id: profile-service
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/api/profile/**
          filters:
            - AuthenticationFilter

  app:
    jwtSecret: "m'rk@ign!12kjegndk;6gkfd\g9fd;dsfm;512dwm*fmig|n"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/